Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Forward the riak control port for one of the nodes
  config.vm.network :forwarded_port, guest: 10069, host: 10069

  # Install the needed puppet modules
  config.vm.provision :shell do |shell|
    shell.inline = "mkdir -p /etc/puppet/modules;
                    puppet module install --force puppetlabs/vcsrepo;
                    puppet module install --force puppetlabs/stdlib;
                    puppet module install --force puppetlabs/apt"
  end

  # Provision the VM
  config.vm.provision :puppet, module_path: "puppet/modules" do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file = "init.pp"
  end
end
